### ISSUE TITLE
db:setup not connecting to RDS

### ISSUE THREAD

**Issue by newbloke82** [infracost/cloud-pricing-api#433]
I've got some difficulties getting the latest image (infracost/cloud-pricing-api:0.3.18) to connect to an RDS instance I've configured to troubleshoot the helm chart.
```
apiVersion: v1
kind: Pod
metadata:
  name: infracost-no-priv
  namespace: default
  labels:
    app.kubernetes.io/name: cloud-pricing-api
spec:
  containers:
  - name: infracost-no-priv
    image: infracost/cloud-pricing-api:0.3.18
    args:
      - sleep
      - "1000000"
    securityContext:
      runAsUser: 1001
```
When I exec into the pod - I can connect to the db using psql ok....
```
kubectl exec -ti -n default infracost-no-priv -- /bin/bash
bash-5.0$ psql \
>    --host=my-rds-instance.oijewoijrowi.eu-central-1.rds.amazonaws.com \
>    --port=5432 \
>    --username=blabla \
>    --password \
>    --dbname=pgsql_multi_az
Password:************
psql (12.10, server 14.8)
WARNING: psql major version 12, server major version 14.
         Some psql features might not work.
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

pgsql_multi_az=> select * from information_schema.columns;
 table_catalog  |    table_schema    |              table_name 
 ```
When I configure the necessary env variables for the pg pool and then try to run db:setup - I get the following errors....
```
bash-5.0$ env|grep POST
POSTGRES_HOST=my-rds-instance.oijewoijrowi.eu-central-1.rds.amazonaws.com
POSTGRES_PASSWORD=************
POSTGRES_USER=blabla
POSTGRES_DB=pgsql_multi_az
bash-5.0$ pwd
/usr/src/app
bash-5.0$ npm run db:setup

> cloud-pricing-api@0.3.18 db:setup
> node dist/cmd/dbSetup.js

{"level":30,"time":1698679277160,"pid":276,"hostname":"infracost-no-priv","msg":"Starting: DB setup"}
{"level":50,"time":1698679277174,"pid":276,"hostname":"infracost-no-priv","msg":"Waiting for PostgreSQL to become available: no pg_hba.conf entry for host \"10.0.43.184\", user \"blabla\", database \"pgsql_multi_az\", no encryption"}
...
{"level":50,"time":1698679377321,"pid":276,"hostname":"infracost-no-priv","err":{"type":"Error","message":"Failed to connect to PostgreSQL","stack":"Error: Failed to connect to PostgreSQL\n    at /usr/src/app/dist/cmd/dbSetup.js:80:31\n    at step (/usr/src/app/dist/cmd/dbSetup.js:33:23)\n    at Object.next (/usr/src/app/dist/cmd/dbSetup.js:14:53)\n    at fulfilled (/usr/src/app/dist/cmd/dbSetup.js:5:58)"},"msg":"Failed to connect to PostgreSQL"}
```
From the error above - the ip address 10.0.43.184 is that of my pod - not the ip address of the database endpoint.

I get the same errors above when configuring the chart.
```
helm install cloud-pricing-api infracost/cloud-pricing-api \
  --set infracostAPIKey="YOUR_INFRACOST_API_KEY_HERE" \
  --set postgresql.enabled="false" \
  --set postgresql.external.host="my-rds-instance.oijewoijrowi.eu-central-1.rds.amazonaws.com" \
  --set postgresql.external.port="5432" \
  --set postgresql.external.database="pgsql_multi_az" \
  --set postgresql.external.user="blabla" \
  --set postgresql.external.password="************"
```
Can you give me any insight please?  Does the db need to be called 'cloud_pricing' and the user set to 'postgres' (the defaults)?

**Comment by newbloke82** [comment]
So this seems related to the RDS being setup with encryption.  I was able to move further by using a different environment variable that you've configured to support postgres connection strings: https://github.com/infracost/cloud-pricing-api/blob/43ee3e013bff296047979255009f8fe7184416d6/src/config.ts#L38
```
bash-5.0$ export POSTGRES_URI="postgresql://blabla:*************@my-rds-instance.oijewoijrowi.eu-central-1.rds.amazonaws.com:5432/pgsql_multi_az?sslmode=require"
bash-5.0$ export NODE_TLS_REJECT_UNAUTHORIZED='0'
bash-5.0$ npm run db:setup

> cloud-pricing-api@0.3.18 db:setup
> node dist/cmd/dbSetup.js

{"level":30,"time":1698681243238,"pid":380,"hostname":"infracost-no-priv","msg":"Starting: DB setup"}
(node:380) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
{"level":30,"time":1698681243441,"pid":380,"hostname":"infracost-no-priv","msg":"Completed: DB setup"}
```
I don't think the current configuration supports supplying the SSL CA cert? I used the big hammer environment variable NODE_TLS_REJECT_UNAUTHORIZED (https://github.com/brianc/node-postgres/issues/2558#issue-907626177).

I've moved a step forward in terms of using an RDS with the cloud-pricing-api but I don't think the helm chart currently allows me to pass the POSTGRES_URI to the init container?  [POSTGRES_URI](https://github.com/infracost/helm-charts/blob/d09a97bf383efc0ac1ed3d12d144a06622170511/charts/cloud-pricing-api/templates/job-init.yaml#L52)
