### ISSUE TITLE
Deploy on local VM fails

### ISSUE THREAD

**Issue by antonbabenko** [infracost/cloud-pricing-api#80]
Hi,

I am not sure what I am doing wrong but I can't make it to run locally using `docker compose`.

Here is the complete log:

```
$ docker-compose up
Creating network "cloud-pricing-api_cloud_pricing_api" with the default driver
Creating volume "cloud-pricing-api_postgres-data" with default driver
Pulling postgres (postgres:13)...
13: Pulling from library/postgres
e1acddbe380c: Pull complete
ab477c15ef75: Pull complete
52fb2eb8fe36: Pull complete
f524381f883e: Pull complete
6814a3f43c00: Pull complete
efeb1f2150cf: Pull complete
de7c6920299d: Pull complete
b8f929d911a2: Pull complete
a961b3c2645a: Pull complete
05a89d8dadc7: Pull complete
ca61de601d6c: Pull complete
0f3fd90b1a40: Pull complete
c4ed85bb4f3a: Pull complete
Digest: sha256:9c8ff3f8c0c9a69e38bb2bf339b34477aa81c69e0df1796bc28f647be504df54
Status: Downloaded newer image for postgres:13
Building init_job
[+] Building 104.2s (18/18) FINISHED                                             
 => [internal] load build definition from Dockerfile                        0.0s
 => => transferring dockerfile: 579B                                        0.0s
 => [internal] load .dockerignore                                           0.0s
 => => transferring context: 181B                                           0.0s
 => [internal] load metadata for docker.io/library/node:14.15.0-alpine3.12  2.0s
 => [auth] library/node:pull token for registry-1.docker.io                 0.0s
 => [internal] load build context                                           0.1s
 => => transferring context: 1.77MB                                         0.1s
 => [build 1/6] FROM docker.io/library/node:14.15.0-alpine3.12@sha256:6864  4.6s
 => => resolve docker.io/library/node:14.15.0-alpine3.12@sha256:6864724c9f  0.0s
 => => sha256:6864724c9f8437ad7fa9fa9c16a1e7e4d985b8418524 1.43kB / 1.43kB  0.0s
 => => sha256:643264cb5398c2afdc864d21ff062166aa06d939c817 1.16kB / 1.16kB  0.0s
 => => sha256:fdcffd80e219a1f6edddfc574c1eaeb050a45326e0ad 6.77kB / 6.77kB  0.0s
 => => sha256:188c0c94c7c576fff0792aca7ec73d67a2f7f4cb3a6e 2.80MB / 2.80MB  0.3s
 => => sha256:09e89cec34b4f7005972acd681fe4dc35dbbe47592 36.12MB / 36.12MB  2.0s
 => => sha256:c2f4cb6c4984b78d814b57bb283675c59a7611ffde44 2.36MB / 2.36MB  0.9s
 => => extracting sha256:188c0c94c7c576fff0792aca7ec73d67a2f7f4cb3a6e53a84  0.3s
 => => sha256:460b6f3ac588718b1a6cc8805dcfce1bc1c7c3867edf4af2 281B / 281B  0.8s
 => => extracting sha256:09e89cec34b4f7005972acd681fe4dc35dbbe4759279ab283  1.9s
 => => extracting sha256:c2f4cb6c4984b78d814b57bb283675c59a7611ffde446ad75  0.2s
 => => extracting sha256:460b6f3ac588718b1a6cc8805dcfce1bc1c7c3867edf4af2c  0.0s
 => [build 2/6] WORKDIR /usr/src/app                                        0.1s
 => [release 2/7] RUN apk update && apk upgrade &&   apk add --no-cache ba  2.4s
 => [build 3/6] COPY package*.json ./                                       0.1s
 => [build 4/6] RUN npm install --production   && cp -R node_modules prod  55.1s
 => [release 3/7] WORKDIR /usr/src/app                                      0.1s
 => [release 4/7] RUN mkdir data                                            0.4s
 => [build 5/6] COPY . .                                                    0.1s
 => [build 6/6] RUN npm run build                                          19.4s 
 => [release 5/7] COPY --from=build /usr/src/app/prod_node_modules ./node_  7.5s 
 => [release 6/7] COPY --from=build /usr/src/app/dist ./dist                0.1s 
 => [release 7/7] COPY package*.json ./                                     0.0s 
 => exporting to image                                                      6.0s 
 => => exporting layers                                                     5.9s 
 => => writing image sha256:59e74b32fc61415e797f7cb1396e8ab9bf47ef5fad8f30  0.0s 
 => => naming to docker.io/infracost/cloud-pricing-api:latest               0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
WARNING: Image for service init_job was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating cloud-pricing-api_postgres_1 ... done
Creating cloud-pricing-api_init_job_1 ... done
Creating cloud-pricing-api_api_1      ... done
Attaching to cloud-pricing-api_postgres_1, cloud-pricing-api_api_1, cloud-pricing-api_init_job_1
postgres_1    | The files belonging to this database system will be owned by user "postgres".
postgres_1    | This user must also own the server process.
postgres_1    | 
postgres_1    | The database cluster will be initialized with locale "en_US.utf8".
postgres_1    | The default database encoding has accordingly been set to "UTF8".
postgres_1    | The default text search configuration will be set to "english".
postgres_1    | 
postgres_1    | Data page checksums are disabled.
postgres_1    | 
postgres_1    | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1    | creating subdirectories ... ok
postgres_1    | selecting dynamic shared memory implementation ... posix
postgres_1    | selecting default max_connections ... 100
postgres_1    | selecting default shared_buffers ... 128MB
postgres_1    | selecting default time zone ... Etc/UTC
postgres_1    | creating configuration files ... ok
postgres_1    | running bootstrap script ... ok
postgres_1    | performing post-bootstrap initialization ... ok
postgres_1    | syncing data to disk ... ok
postgres_1    | 
postgres_1    | initdb: warning: enabling "trust" authentication for local connections
postgres_1    | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1    | --auth-local and --auth-host, the next time you run initdb.
postgres_1    | 
postgres_1    | Success. You can now start the database server using:
postgres_1    | 
postgres_1    |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1    | 
postgres_1    | waiting for server to start....2021-08-19 11:20:52.216 UTC [36] LOG:  starting PostgreSQL 13.4 (Debian 13.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres_1    | 2021-08-19 11:20:52.221 UTC [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1    | 2021-08-19 11:20:52.230 UTC [37] LOG:  database system was shut down at 2021-08-19 11:20:51 UTC
postgres_1    | 2021-08-19 11:20:52.240 UTC [36] LOG:  database system is ready to accept connections
postgres_1    |  done
postgres_1    | server started
postgres_1    | CREATE DATABASE
postgres_1    | 
postgres_1    | 
postgres_1    | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1    | 
postgres_1    | waiting for server to shut down....2021-08-19 11:20:52.707 UTC [36] LOG:  received fast shutdown request
postgres_1    | 2021-08-19 11:20:52.710 UTC [36] LOG:  aborting any active transactions
postgres_1    | 2021-08-19 11:20:52.715 UTC [36] LOG:  background worker "logical replication launcher" (PID 43) exited with exit code 1
postgres_1    | 2021-08-19 11:20:52.717 UTC [38] LOG:  shutting down
postgres_1    | 2021-08-19 11:20:52.742 UTC [36] LOG:  database system is shut down
postgres_1    |  done
postgres_1    | server stopped
postgres_1    | 
postgres_1    | PostgreSQL init process complete; ready for start up.
postgres_1    | 
postgres_1    | 2021-08-19 11:20:52.833 UTC [1] LOG:  starting PostgreSQL 13.4 (Debian 13.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres_1    | 2021-08-19 11:20:52.833 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1    | 2021-08-19 11:20:52.833 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1    | 2021-08-19 11:20:52.838 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1    | 2021-08-19 11:20:52.844 UTC [64] LOG:  database system was shut down at 2021-08-19 11:20:52 UTC
postgres_1    | 2021-08-19 11:20:52.851 UTC [1] LOG:  database system is ready to accept connections
init_job_1    | 
init_job_1    | > cloud-pricing-api@0.2.0 job:init /usr/src/app
init_job_1    | > npm run db:setup && npm run job:update
init_job_1    | 
api_1         | 
api_1         | > cloud-pricing-api@0.2.0 start /usr/src/app
api_1         | > node dist/server.js
api_1         | 
api_1         | internal/modules/cjs/loader.js:883
api_1         |   throw err;
api_1         |   ^
api_1         | 
api_1         | Error: Cannot find module '/usr/src/app/dist/server.js'
api_1         |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
api_1         |     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
api_1         |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
api_1         |     at internal/main/run_main_module.js:17:47 {
api_1         |   code: 'MODULE_NOT_FOUND',
api_1         |   requireStack: []
api_1         | }
api_1         | npm ERR! code ELIFECYCLE
api_1         | npm ERR! errno 1
api_1         | npm ERR! cloud-pricing-api@0.2.0 start: `node dist/server.js`
api_1         | npm ERR! Exit status 1
api_1         | npm ERR! 
api_1         | npm ERR! Failed at the cloud-pricing-api@0.2.0 start script.
api_1         | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
api_1         | 
api_1         | npm ERR! A complete log of this run can be found in:
api_1         | npm ERR!     /root/.npm/_logs/2021-08-19T11_20_53_136Z-debug.log
cloud-pricing-api_api_1 exited with code 1
init_job_1    | 
init_job_1    | > cloud-pricing-api@0.2.0 db:setup /usr/src/app
init_job_1    | > node dist/cmd/dbSetup.js
init_job_1    | 
init_job_1    | internal/modules/cjs/loader.js:883
init_job_1    |   throw err;
init_job_1    |   ^
init_job_1    | 
init_job_1    | Error: Cannot find module '/usr/src/app/dist/cmd/dbSetup.js'
init_job_1    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
init_job_1    |     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
init_job_1    |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
init_job_1    |     at internal/main/run_main_module.js:17:47 {
init_job_1    |   code: 'MODULE_NOT_FOUND',
init_job_1    |   requireStack: []
init_job_1    | }
init_job_1    | npm ERR! code ELIFECYCLE
init_job_1    | npm ERR! errno 1
init_job_1    | npm ERR! cloud-pricing-api@0.2.0 db:setup: `node dist/cmd/dbSetup.js`
init_job_1    | npm ERR! Exit status 1
init_job_1    | npm ERR! 
init_job_1    | npm ERR! Failed at the cloud-pricing-api@0.2.0 db:setup script.
init_job_1    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
init_job_1    | 
init_job_1    | npm ERR! A complete log of this run can be found in:
init_job_1    | npm ERR!     /root/.npm/_logs/2021-08-19T11_20_53_794Z-debug.log
init_job_1    | npm ERR! code ELIFECYCLE
init_job_1    | npm ERR! errno 1
init_job_1    | npm ERR! cloud-pricing-api@0.2.0 job:init: `npm run db:setup && npm run job:update`
init_job_1    | npm ERR! Exit status 1
init_job_1    | npm ERR! 
init_job_1    | npm ERR! Failed at the cloud-pricing-api@0.2.0 job:init script.
init_job_1    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
init_job_1    | 
init_job_1    | npm ERR! A complete log of this run can be found in:
init_job_1    | npm ERR!     /root/.npm/_logs/2021-08-19T11_20_53_845Z-debug.log
cloud-pricing-api_init_job_1 exited with code 1
```

**Comment by aliscott** [comment]
@antonbabenko thanks for reporting.
Which version of docker and docker-compose is this with?

**Comment by antonbabenko** [comment]
```
$ docker --version
Docker version 20.10.7, build f0df350
$ docker-compose --version
docker-compose version 1.29.2, build 5becea4c
```

I am using Mac OS 11.5.2

**Comment by aliscott** [comment]
Thanks, I've tried reproducing but unable to. It looks odd since the files in the `dist` directory don't exist.

Are you able to try the following:
1. `docker-compose run api ls -lah {.,dist}` and paste the output
2. Run the following and see if it works:

```
# cleanup existing
docker-compose rm
docker volume rm cloud-pricing-api_postgres-data
docker rmi infracost/cloud-pricing-api:latest

# pull images
docker-compose pull
# run
docker-compose up
```

**Comment by antonbabenko** [comment]
This was the output:

```
$ docker-compose run api ls -lah {.,dist}
Starting cloud-pricing-api_postgres_1 ... done
Creating cloud-pricing-api_api_run    ... done
.:
total 716K   
drwxr-xr-x    1 root     root        4.0K Aug 19 11:20 .
drwxr-xr-x    1 root     root        4.0K Aug 19 11:19 ..
drwxr-xr-x    3 root     root          96 Aug 19 11:14 data
drwxr-xr-x    4 root     root        4.0K Aug 19 11:20 dist
drwxr-xr-x  340 root     root       12.0K Aug 19 11:20 node_modules
-rw-r--r--    1 root     root      682.7K Aug 19 11:14 package-lock.json
-rw-r--r--    1 root     root        3.2K Aug 19 11:14 package.json

dist:
total 16K    
drwxr-xr-x    4 root     root        4.0K Aug 19 11:20 .
drwxr-xr-x    1 root     root        4.0K Aug 19 11:20 ..
drwxr-xr-x    5 root     root        4.0K Aug 19 11:20 public
drwxr-xr-x    3 root     root        4.0K Aug 19 11:20 views
```

Running the command you provided did the trick and it works well now.

The issue can be closed. Let me know if I can provide a more useful debug data.

**Comment by aliscott** [comment]
Thanks @antonbabenko, looks like something went wrong with the docker build. If you're able to reproduce again it would be good to see the output of `docker-compose build --no-cache --progress plain`.

I'll close this issue for now.
